### ISSUE TITLE
Error in package.json results in "npm command not found"

### ISSUE THREAD

**Issue by espositoandrea** [timonweb/django-tailwind#100]
Hi,
I'm currently using the latest pip version of this package. When I run `python manage.py tailwind install` everything runs fine and smoothly, but then if I run `python manage.py tailwind start` the following error occurs (pasting the full output):

```
> theme@2.2.1 start
> npm run dev


> theme@2.2.1 dev
> nodemon -x \"npm run dev:sync\" -w tailwind.config.js -w postcss.config.js -w bs.config.js -e js

[nodemon] 2.0.13
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): tailwind.config.js postcss.config.js bs.config.js
[nodemon] watching extensions: js
[nodemon] starting `"npm run dev:sync"`
sh: npm run dev:sync: command not found
[nodemon] failed to start process, ""npm" exec not found
[nodemon] Error
    at Bus.<anonymous> (/Users/andrea/Downloads/survey/src/visualization/static_src/node_modules/nodemon/lib/nodemon.js:158:25)
    at Bus.emit (node:events:402:35)
    at ChildProcess.<anonymous> (/Users/andrea/Downloads/survey/src/visualization/static_src/node_modules/nodemon/lib/monitor/run.js:190:11)
    at ChildProcess.emit (node:events:390:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
```

As you can see, nodemon searches for the `"npm"` command (note the double quotes repeated two times in the above). I fixed this error by simply editing the `package.json` file (basically, the backslash was escaped):

```diff
...
  "scripts": {
    "start": "npm run dev",
    "build": "npm run build:clean && npm run build:tailwind",
    "build:clean": "rimraf ../static/css/dist",
    "build:tailwind": "cross-env NODE_ENV=production tailwindcss --postcss -i src/styles.css -o ../static/css/dist/styles.css --minify",
    "sync": "browser-sync start --config bs.config.js",
    "dev:tailwind": "cross-env NODE_ENV=development tailwindcss --postcss -i src/styles.css -o ../static/css/dist/styles.css -w",
    "dev:sync": "run-p dev:tailwind sync",
-    "dev": "nodemon -x \\\"npm run dev:sync\\\" -w tailwind.config.js -w postcss.config.js -w bs.config.js -e js",
+    "dev": "nodemon -x \"npm run dev:sync\" -w tailwind.config.js -w postcss.config.js -w bs.config.js -e js",
    "tailwindcss": "node ./node_modules/tailwindcss/lib/cli.js"
  },
...
```

I was not able to find the same issue in the code here on GitHub, so I'm creating this issue so that the maintainer can give me a pointer to what file to edit in a PR (if this issue has not been already solved).

Thanks in advance.

**Comment by timonweb** [comment]
Hi @espositoandrea, what's your OS?

**Comment by espositoandrea** [comment]
Hi. I had this issue while using MacOS Big Sur 11.6 running on the Apple M1.

**Comment by timonweb** [comment]
Good, our current template uses single `\` (https://github.com/timonweb/django-tailwind/blob/master/src/tailwind/app_template_v2/%7B%7Bcookiecutter.app_name%7D%7D/static_src/package.json#L13) so it looks like we're good.
