### ISSUE TITLE
setup.py egg_info UnicodeDecodeError

### ISSUE THREAD

**Issue by ayazamlani** [timonweb/django-tailwind#2]
### I have anaconda. However, even if I use venv or pipenv for some reason I still get this error. It may be because I have anaconda installed?

```
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "~\Temp\pip-install-owbdvwgs\django-tailwind\setup.py", line 10, in <module>
        long_description=open("README.md").read(),
      File "~\Anaconda3\envs\mls\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 84: character maps to <undefined>
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in ~\Temp\pip-install-owbdvwgs\django-tailwind\
```

**Comment by timonweb** [comment]
Hmm, it looks like emoji "❤️" in README.md breaks the code. I've enforced "utf-8" and updated package to 0.5.6, please try to reinstall `pip install django-tailwind --upgrade` and let me know if that helped.

**Comment by ayazamlani** [comment]
`Successfully installed django-tailwind-0.5.6`

**Comment by timonweb** [comment]
👍
