### ISSUE TITLE
won't start in dev mode

### ISSUE THREAD

**Issue by jyoost** [timonweb/django-tailwind#93]
I get the following Error when running   python manage.py tailwind start   : 

[nodemon] app crashed - waiting for file changes before starting...

more debug:

TypeError: Object.fromEntries is not a function
    at Object.<anonymous> (/home/jyoost/PycharmProjects/bakerydemo/theme/static_src/node_modules/tailwindcss/lib/jit/corePlugins.js:242:13)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/jyoost/PycharmProjects/bakerydemo/theme/static_src/node_modules/tailwindcss/lib/jit/lib/setupContextUtils.js:36:43)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
ERROR: "dev:tailwind" exited with 1.

**Comment by jyoost** [comment]
updated npm and nodejs. downloaded latest package from tailwind. fixed
